In [1]:
import mysql.connector

In [20]:
#conexão com o banco de dados para capturar as solicitações desejadas
con = mysql.connector.connect(host="#######", user="#######", passwd="#######", db="#######")
sql = con.cursor()
query = "select user_id, sum(valor) as valor from pretendente_produto where month(payment_at) = 9 and year(payment_at) = 2021 group by user_id"
sql.execute(query)

In [21]:
for res in sql:
    print("update administradora_funcionario set credito_utilizado = "+str(res[1])+" where user_id = "+str(res[0])+";")

update administradora_funcionario set credito_utilizado = 0.04 where user_id = 3;
update administradora_funcionario set credito_utilizado = 36.00 where user_id = 459;
update administradora_funcionario set credito_utilizado = 54.00 where user_id = 460;
update administradora_funcionario set credito_utilizado = 18.00 where user_id = 789;
update administradora_funcionario set credito_utilizado = 150.00 where user_id = 2637;
update administradora_funcionario set credito_utilizado = 162.00 where user_id = 2733;
update administradora_funcionario set credito_utilizado = 528.00 where user_id = 2916;
update administradora_funcionario set credito_utilizado = 480.00 where user_id = 2948;
update administradora_funcionario set credito_utilizado = 275.00 where user_id = 3043;
update administradora_funcionario set credito_utilizado = 54.00 where user_id = 3106;
update administradora_funcionario set credito_utilizado = 140.00 where user_id = 3251;
update administradora_funcionario set credito_utilizado = 40.00 where user_id = 3252;
update administradora_funcionario set credito_utilizado = 325.00 where user_id = 3516;
update administradora_funcionario set credito_utilizado = 324.00 where user_id = 4235;
update administradora_funcionario set credito_utilizado = 160.00 where user_id = 4256;
update administradora_funcionario set credito_utilizado = 75.00 where user_id = 4441;
update administradora_funcionario set credito_utilizado = 200.00 where user_id = 4707;
update administradora_funcionario set credito_utilizado = 75.00 where user_id = 5370;
update administradora_funcionario set credito_utilizado = 150.00 where user_id = 6168;
update administradora_funcionario set credito_utilizado = 300.00 where user_id = 6672;
update administradora_funcionario set credito_utilizado = 150.00 where user_id = 6673;
update administradora_funcionario set credito_utilizado = 805.00 where user_id = 7250;
update administradora_funcionario set credito_utilizado = 56.00 where user_id = 7366;
update administradora_funcionario set credito_utilizado = 112.00 where user_id = 7368;
update administradora_funcionario set credito_utilizado = 168.00 where user_id = 7370;
update administradora_funcionario set credito_utilizado = 270.00 where user_id = 7371;
update administradora_funcionario set credito_utilizado = 54.00 where user_id = 7775;
update administradora_funcionario set credito_utilizado = 36.00 where user_id = 8268;
update administradora_funcionario set credito_utilizado = 775.00 where user_id = 9300;
update administradora_funcionario set credito_utilizado = 48.00 where user_id = 10192;
update administradora_funcionario set credito_utilizado = 120.00 where user_id = 10193;
update administradora_funcionario set credito_utilizado = 276.00 where user_id = 10196;
update administradora_funcionario set credito_utilizado = 132.00 where user_id = 10199;
update administradora_funcionario set credito_utilizado = 96.00 where user_id = 10202;
update administradora_funcionario set credito_utilizado = 72.00 where user_id = 10210;
update administradora_funcionario set credito_utilizado = 156.00 where user_id = 10211;
update administradora_funcionario set credito_utilizado = 156.00 where user_id = 10215;
update administradora_funcionario set credito_utilizado = 120.00 where user_id = 10216;
update administradora_funcionario set credito_utilizado = 36.00 where user_id = 10217;
update administradora_funcionario set credito_utilizado = 60.00 where user_id = 10219;
update administradora_funcionario set credito_utilizado = 60.00 where user_id = 10220;
update administradora_funcionario set credito_utilizado = 108.00 where user_id = 10221;
update administradora_funcionario set credito_utilizado = 72.00 where user_id = 10223;
update administradora_funcionario set credito_utilizado = 288.00 where user_id = 11618;
update administradora_funcionario set credito_utilizado = 154.00 where user_id = 11671;
update administradora_funcionario set credito_utilizado = 24.00 where user_id = 13202;
update administradora_funcionario set credito_utilizado = 30.00 where user_id = 14895;
update administradora_funcionario set credito_utilizado = 224.00 where user_id = 16826;
update administradora_funcionario set credito_utilizado = 18.01 where user_id = 17675;
update administradora_funcionario set credito_utilizado = 19.00 where user_id = 17924;
update administradora_funcionario set credito_utilizado = 19.00 where user_id = 17935;
update administradora_funcionario set credito_utilizado = 114.00 where user_id = 17937;
update administradora_funcionario set credito_utilizado = 204.00 where user_id = 24454;
update administradora_funcionario set credito_utilizado = 48.00 where user_id = 24828;
update administradora_funcionario set credito_utilizado = 54.00 where user_id = 25915;
update administradora_funcionario set credito_utilizado = 150.00 where user_id = 27088;
update administradora_funcionario set credito_utilizado = 116.00 where user_id = 27136;
update administradora_funcionario set credito_utilizado = 84.00 where user_id = 27606;
update administradora_funcionario set credito_utilizado = 14.00 where user_id = 27614;
update administradora_funcionario set credito_utilizado = 330.00 where user_id = 28618;
update administradora_funcionario set credito_utilizado = 30.00 where user_id = 28653;
update administradora_funcionario set credito_utilizado = 30.00 where user_id = 28762;
update administradora_funcionario set credito_utilizado = 306.00 where user_id = 29157;
update administradora_funcionario set credito_utilizado = 270.00 where user_id = 30660;
update administradora_funcionario set credito_utilizado = 38.00 where user_id = 30795;
update administradora_funcionario set credito_utilizado = 19.00 where user_id = 31103;
update administradora_funcionario set credito_utilizado = 57.00 where user_id = 31104;
update administradora_funcionario set credito_utilizado = 114.00 where user_id = 31105;
update administradora_funcionario set credito_utilizado = 133.00 where user_id = 31107;
update administradora_funcionario set credito_utilizado = 768.00 where user_id = 32126;
update administradora_funcionario set credito_utilizado = 322.00 where user_id = 34070;
update administradora_funcionario set credito_utilizado = 108.00 where user_id = 34093;
update administradora_funcionario set credito_utilizado = 72.00 where user_id = 34387;
update administradora_funcionario set credito_utilizado = 57.00 where user_id = 34487;
update administradora_funcionario set credito_utilizado = 38.00 where user_id = 34679;
update administradora_funcionario set credito_utilizado = 114.00 where user_id = 34682;
update administradora_funcionario set credito_utilizado = 323.00 where user_id = 34685;
update administradora_funcionario set credito_utilizado = 57.00 where user_id = 34686;
update administradora_funcionario set credito_utilizado = 19.00 where user_id = 34721;
update administradora_funcionario set credito_utilizado = 57.00 where user_id = 34725;
update administradora_funcionario set credito_utilizado = 19.00 where user_id = 34726;
update administradora_funcionario set credito_utilizado = 19.00 where user_id = 34771;
update administradora_funcionario set credito_utilizado = 38.00 where user_id = 34807;
update administradora_funcionario set credito_utilizado = 76.00 where user_id = 34808;
update administradora_funcionario set credito_utilizado = 391.00 where user_id = 35244;
update administradora_funcionario set credito_utilizado = 306.00 where user_id = 35417;
update administradora_funcionario set credito_utilizado = 119.00 where user_id = 36155;
update administradora_funcionario set credito_utilizado = 180.00 where user_id = 37030;
update administradora_funcionario set credito_utilizado = 30.00 where user_id = 37541;
update administradora_funcionario set credito_utilizado = 60.00 where user_id = 37847;
update administradora_funcionario set credito_utilizado = 76.00 where user_id = 39075;
update administradora_funcionario set credito_utilizado = 209.00 where user_id = 39081;
update administradora_funcionario set credito_utilizado = 95.00 where user_id = 40387;
update administradora_funcionario set credito_utilizado = 76.00 where user_id = 40905;
update administradora_funcionario set credito_utilizado = 155.00 where user_id = 41624;
update administradora_funcionario set credito_utilizado = 152.00 where user_id = 41842;
update administradora_funcionario set credito_utilizado = 112.00 where user_id = 42405;
update administradora_funcionario set credito_utilizado = 85.00 where user_id = 43610;
update administradora_funcionario set credito_utilizado = 1476.00 where user_id = 44271;
update administradora_funcionario set credito_utilizado = 130.00 where user_id = 44338;
update administradora_funcionario set credito_utilizado = 19.00 where user_id = 46094;
update administradora_funcionario set credito_utilizado = 156.00 where user_id = 46138;
update administradora_funcionario set credito_utilizado = 20.00 where user_id = 46738;
update administradora_funcionario set credito_utilizado = 209.00 where user_id = 47273;
update administradora_funcionario set credito_utilizado = 850.00 where user_id = 47761;
update administradora_funcionario set credito_utilizado = 510.00 where user_id = 49485;
update administradora_funcionario set credito_utilizado = 112.00 where user_id = 49534;
update administradora_funcionario set credito_utilizado = 276.00 where user_id = 49848;
update administradora_funcionario set credito_utilizado = 12.00 where user_id = 49849;
update administradora_funcionario set credito_utilizado = 336.00 where user_id = 49885;
update administradora_funcionario set credito_utilizado = 120.00 where user_id = 51633;
update administradora_funcionario set credito_utilizado = 38.00 where user_id = 51952;
update administradora_funcionario set credito_utilizado = 252.20 where user_id = 51972;
update administradora_funcionario set credito_utilizado = 95.00 where user_id = 52687;
update administradora_funcionario set credito_utilizado = 76.00 where user_id = 52706;
update administradora_funcionario set credito_utilizado = 76.00 where user_id = 53615;
update administradora_funcionario set credito_utilizado = 171.00 where user_id = 53961;
update administradora_funcionario set credito_utilizado = 375.00 where user_id = 56157;
update administradora_funcionario set credito_utilizado = 120.00 where user_id = 58602;
update administradora_funcionario set credito_utilizado = 60.05 where user_id = 59709;
update administradora_funcionario set credito_utilizado = 95.00 where user_id = 60054;
update administradora_funcionario set credito_utilizado = 90.00 where user_id = 60334;
update administradora_funcionario set credito_utilizado = 60.00 where user_id = 60951;
update administradora_funcionario set credito_utilizado = 180.00 where user_id = 60954;
update administradora_funcionario set credito_utilizado = 57.00 where user_id = 61204;
update administradora_funcionario set credito_utilizado = 50.00 where user_id = 61789;
update administradora_funcionario set credito_utilizado = 972.00 where user_id = 63321;
update administradora_funcionario set credito_utilizado = 76.00 where user_id = 63696;
update administradora_funcionario set credito_utilizado = 125.00 where user_id = 63923;
update administradora_funcionario set credito_utilizado = 100.00 where user_id = 64611;
update administradora_funcionario set credito_utilizado = 187.00 where user_id = 64965;
update administradora_funcionario set credito_utilizado = 60.00 where user_id = 65073;
update administradora_funcionario set credito_utilizado = 190.00 where user_id = 67030;
update administradora_funcionario set credito_utilizado = 14.00 where user_id = 70238;
update administradora_funcionario set credito_utilizado = 50.00 where user_id = 70475;
update administradora_funcionario set credito_utilizado = 75.00 where user_id = 70478;
update administradora_funcionario set credito_utilizado = 95.00 where user_id = 73665;
update administradora_funcionario set credito_utilizado = 275.00 where user_id = 74851;
update administradora_funcionario set credito_utilizado = 18.00 where user_id = 76477;
update administradora_funcionario set credito_utilizado = 150.00 where user_id = 76877;
update administradora_funcionario set credito_utilizado = 120.00 where user_id = 78039;
update administradora_funcionario set credito_utilizado = 156.00 where user_id = 78400;
update administradora_funcionario set credito_utilizado = 50.00 where user_id = 79476;
update administradora_funcionario set credito_utilizado = 18.00 where user_id = 81056;
update administradora_funcionario set credito_utilizado = 36.00 where user_id = 81329;
update administradora_funcionario set credito_utilizado = 126.00 where user_id = 82398;
update administradora_funcionario set credito_utilizado = 144.00 where user_id = 82400;
update administradora_funcionario set credito_utilizado = 18.00 where user_id = 82401;
update administradora_funcionario set credito_utilizado = 150.00 where user_id = 82633;
update administradora_funcionario set credito_utilizado = 45.00 where user_id = 85349;
update administradora_funcionario set credito_utilizado = 175.00 where user_id = 86936;
update administradora_funcionario set credito_utilizado = 76.00 where user_id = 87447;
update administradora_funcionario set credito_utilizado = 32.00 where user_id = 88021;
update administradora_funcionario set credito_utilizado = 50.00 where user_id = 88316;
update administradora_funcionario set credito_utilizado = 90.00 where user_id = 88927;
update administradora_funcionario set credito_utilizado = 48.00 where user_id = 89368;
update administradora_funcionario set credito_utilizado = 72.00 where user_id = 89640;